DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    city_id INT NOT NULL,
    firs_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (city_id) REFERENCES cities(id)
);