DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO accounts(name,balance)
VALUES('Bob',10000);

-- For begining a transaction

BEGIN;

INSERT INTO accounts(name,balance)
VALUES('Alice',10000);


SELECT 
    id,
    name,
    balance
FROM 
    accounts;


    -- start a transaction
BEGIN;

-- insert a new row into the accounts table
INSERT INTO accounts(name,balance)
VALUES('Ola',100000);

-- commit the change (or roll it back later)
COMMIT;



-- Performing debit transactions

BEGIN

UPDATE accounts 
SET balance = balance - 1000
WHERE id = 1;


UPDATE accounts
SET balance = balance + 1000
WHERE id = 3; 
